### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/icfpc-2017#1]
I propose to use MIT license for our code in the repository. Are everyone okay with that?

cc @portnov @Minoru @Akon32

**Comment by Akon32** [comment]
It's ok.

**Comment by Minoru** [comment]
I'm fine with that.

**Comment by portnov** [comment]
i'm fine too.

**Comment by ForNeVeR** [comment]
Thank you, guys!
